version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./volume_mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: desafio_rails_development
      MYSQL_USER: danilo
      MYSQL_PASSWORD: danilo
    networks:
      - desafio-network
  desafio_rails:
    build: .
    command: bash -c "rm config/database.yml && cp config/database.docker.yml config/database.yml && rake db:create && rake db:migrate && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "80:3000"
    image: didox/rails_desafio
    depends_on:
      - db
    links:
      - db
    networks:
      - desafio-network

networks: 
  desafio-network:
    driver: bridge
    
