default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: root
  host: 192.168.0.22

development:
  <<: *default
  database: desafio_rails_development

test:
  <<: *default
  database: desafio_rails_test

production:
  <<: *default
  database: <%= ENV['DATABASE'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASS'] %>
  host: <%= ENV['DATABASE_HOST'] %>